name: Deploy terraform infrastructure

on:
  push:
    branches: [ "dev", "staging", "main" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"
  ENVIRONMENT_STAGE: ${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/staging' && 'staging') || 'dev' }}

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./root/project-x/
        shell: bash

    environment: ${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/staging' && 'staging') || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::537479208195:role/github_actions_role
          role-session-name: GitHubActionRoleSession
          aws-region: ${{ env.AWS_REGION }}

      - name: Check commit message
        id: check_message
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"destroy cluster"* ]]; then
            echo "action=destroy" >> $GITHUB_ENV
          elif [[ "${{ github.event.head_commit.message }}" == *"deploy cluster"* ]]; then
            echo "action=deploy" >> $GITHUB_ENV
          else
            echo "action=none" >> $GITHUB_ENV
          fi

      - name: Stop if no relevant action
        if: env.action == 'none'
        run: echo "No deploy or destroy action found in commit message. Exiting."

      - name: Terraform init
        if: env.action != 'none'
        run: terraform init -backend-config="bucket=project-x-stat-bucket-ilya-${ENVIRONMENT_STAGE}" -backend-config="key=eks-cluster-${ENVIRONMENT_STAGE}/terraform.tfstate" -backend-config="region=${AWS_REGION}" -backend-config="dynamodb_table=terraform-dynamodb-lock-table-${ENVIRONMENT_STAGE}"

      - name: Terraform Format
        if: env.action != 'none'
        run: |
          terraform fmt
          terraform fmt -check

      - name: Terraform Plan
        if: env.action != 'none'
        run: terraform plan -input=false -var-file="${ENVIRONMENT_STAGE}.tfvars"

      - name: Terraform Apply or Destroy
        if: env.action == 'deploy'
        run: terraform apply -auto-approve -input=false -var-file="${ENVIRONMENT_STAGE}.tfvars"

      - name: Terraform Apply or Destroy
        if: env.action == 'destroy'
        run: terraform destroy -auto-approve -input=false -var-file="${ENVIRONMENT_STAGE}.tfvars"
